#!/usr/bin/env php
<?php

use Realodix\Haiku\Console\Kernel;

$possibleFiles = [
    __DIR__.'/../../autoload.php',
    __DIR__.'/../autoload.php',
    __DIR__.'/vendor/autoload.php',
];
$found = false;
foreach ($possibleFiles as $file) {
    if (file_exists($file)) {
        require_once $file;
        $found = true;
        break;
    }
}
if (!$found) {
    exit('Unable to locate Composer\'s autoload.php file. Did you run "composer install"?');
}


$kernel = new Kernel;
exit($kernel->handle());
